### ISSUE TITLE
Header covers the page partially

### ISSUE THREAD

**Issue by chrisjwelly** [nuansa-cp/gapura#24]
Below shows a screenshot from Firefox (left) and Chrome (right). 
![](https://imgur.com/Rl55Cq4.png)

The header seems to cover the page partially. This is not obvious in full screen, but it is apparent when I squeeze the page to half screen like the screenshot above ('Lukisan Jati' is partially covered)

This issue is persistent in the pull request that I am working on (#23), as the past NUANSA page I'm redesigning is always partially blocked in the web version

**Comment by stevenwjy** [comment]
Solved in #26 for iPad display (or similar size, max-width around 1200px). 

However, it seems like for iPad pro size (around 1300px) there are still some problems, especially because it will try to render the split display (like for web view) while the width is not large enough to display the full picture, hence causing the background image (previous NUANSA photo) to be displayed partially (only around half of it)
